### ISSUE TITLE
Kobold fails to launch (ROCm)

### ISSUE THREAD

**Issue by EeduWave** [LostRuins/koboldcpp#1123]
I've been trying to use Kobold locally on my computer. However, every time I try to launch it the launching fails and KoboldCPP immediately closes/crashes. Trying to figure out what's happening is painful, since it takes an average of 4-5 minutes for Kobold to properly show the GUI and give me the ability to launch it - which then it proceeds to fail.

Here are screenshots of KoboldCPP seconds before it closes.

This one is what it shows when I use hipBLAS
![KAI01](https://github.com/user-attachments/assets/bea832d5-3c41-4ec1-8e52-8aa24a617f0e)
(Portuguese text translation: [WinError 1114] A dynamic link library (DLL) initialization routine failed)

I've tried alternatively with the Vulkan option (probably unrelated, just did it to try if it changed anything), it instead gives me a different error
![KAI02](https://github.com/user-attachments/assets/2fddce05-9171-4e18-9444-6ca13ce0bdfe)

Here are my computer specs, in case it helps:
Windows 10 Pro x64-based PC 22H2 
Intel(R) Pentium(R) Gold G5400 CPU @ 3.70GHz / Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~3696 Mhz (AMD)

I have very little coding knowledge, so any help is welcome!

**Comment by LostRuins** [comment]
Hi,

The problem is that your CPU `Intel(R) Pentium(R) Gold G5400 CPU ` does not support AVX or AVX2, thus it's unable to use any SIMD instructions.

Do you have a GPU? If so, what GPU is it?

Right now, the only option that will work is "Failsafe" CPU mode, you can try that. Also, the model you selected is likely going to be too slow for you, try this one: https://huggingface.co/concedo/KobbleTinyV2-1.1B-GGUF/resolve/main/KobbleTiny-Q4_K.gguf?download=true

**Comment by EeduWave** [comment]
My GPU is Radeon RX 570 Series.

Oh, and this is the error that appeared using the Failsafe mode.

![KAI03](https://github.com/user-attachments/assets/552e804e-d30a-4782-9df8-8f38b82880c3)

**Comment by EeduWave** [comment]
Wrong button, oops.

**Comment by henk717** [comment]
The RX570 does not support ROCm, you would have to use Vulkan but you'd still be CPU limited.
