### ISSUE TITLE
Add a Translator to translate User text into English

### ISSUE THREAD

**Issue by Vladonai** [LostRuins/koboldcpp#114]
Some people can read English, but they have difficulty composing long sentences in that language. This makes communicating with a neural network uncomfortable. It would be nice to add the ability to enable Google Translator (deep_translator as an example), which would allow you to enter sentences in your native language into inputbox, and when you press Enter the neural network would be sent the English translation.

**Comment by artemcrum** [comment]
Voting for this improvement. Oobabooga has an extension for that. Would be nice to hove something like that in Kobold.ccp.

**Comment by janvarev** [comment]
Also vote for this improvement. I've made some work for Oobabooga translate extension, but wanna see the same functionality here.

I've also made some simple REST service if you plan to integrate translations (custom translation plugins supported, simple Windows installation supported):
https://github.com/janvarev/OneRingTranslator

May be it's better to integrate this instead of just one Google Translator.

**Comment by janvarev** [comment]
...I even wanna see back translation from LLM response..
Oobabooga save an English version of each message, and version on User language.

**Comment by Vladonai** [comment]
Yes, but it should be optional. The reverse translation from English is of poor quality.

**Comment by janvarev** [comment]
It depends on language, but I agreed - it's better to have an option.

**Comment by janvarev** [comment]
I've made some solution: proxy KoboldAPI translation server
https://github.com/janvarev/kobold_api_multilang_proxy
