### ISSUE TITLE
koboldcpp slows down when the program minimized or run on the background.

### ISSUE THREAD

**Issue by meAlphanism** [LostRuins/koboldcpp#1180]
**Describe the Issue**
Hello, everyone. I would like to raise a question also help regarding to my koboldcpp that somehow slows down everytime the program minimized or run before my browser.

I used my koboldcpp with an 8B model alongside with SillyTavern. Everytime I requested for generation from the front, everything went okay including the BLAS processing. But when it comes into the generation phase, it always slows down with an exception if I opened my koboldcpp window, it goes normal again until I minimized it or moved back to my browser. I suspected this to be my own performance issue and or idling slowdown issue.

I usually run koboldcpp by disabling mmap, keep foreground, and runs with 8192 tokens for context size (w/ Context Shift).

Can anyone give me at least an explanation for this? I'm looking further for help, thanks!

**Additional Information:**
```
Operating System: Windows 11 Home Single Language 64-bit (10.0, Build 22631) (22621.ni_release.220506-1250)
Processor: 12th Gen Intel(R) Core(TM) i5-12450H (12 CPUs), ~2.0GHz
Memory: 8192MB RAM
Card name: NVIDIA GeForce RTX 3050 6GB Laptop GPU
koboldcpp Version: Release 1.76
```

**Comment by LostRuins** [comment]
This is caused by poor efficiency core scheduling on Intel 12th gen and above CPUs, your PC is assigning KoboldCpp lousy "E" cores by mistake.

Here are a few things you can try, try each one and see if it helps:
- **FIRST, TRY THIS:** Use fewer threads. Since you only have 4 P-cores, try setting the thread count `--threads` to 4.
- Use the `--foreground` flag, which tries to bring the window to the foreground when a new request comes in. May not work well on windows 11.
- Use the `--highpriority` flag or toggle to increase process priority
- - Set process affinity (complex), you can use Process Lasso (tool) to prevent E-Cores from being used.

**Comment by meAlphanism** [comment]
This is GREAT! Thank you very much for the response and solution, it seems to worked out very well!

**Comment by LostRuins** [comment]
Please do share which method works best for you.
