### ISSUE TITLE
Output to console under Linux delayed

### ISSUE THREAD

**Issue by AllesMeins** [LostRuins/koboldcpp#122]
So this is not really a bug, more of a little annoyance. 

I've run koboldcpp on both Linux and Windows and one thing I noticed is that parts of the console-output in Linux gets delayed until after a task is done. So when I insert a new prompt under Windows I get the information "Processing Prompt [BLAS] (851 / 851 tokens)" and "Generating (8 / 8 tokens)" at the start of the processing and regular updates while the job is processed. So I know what is going on. Under Linux these information are only displayed after all the work is done - so I've no idea what is currently going on or what is taking so long. I think there might be some kind of "flush" or similar command missing that refreshes the output in Linux?

As far as I can see this only concerns those outputs that are not produced by python directly but by the C++ libs. Thy python output like ´print("\nInput: " + json.dumps(genparams))´ is displayed without delay.
I know this is not really important, but maybe it is also a quick fix? Unfortunately I don't know enough about C-programming to fix it myself.

**Comment by LostRuins** [comment]
Should be fixed in the latest commit.

**Comment by bucketcat** [comment]
Dunno if related, but on ubuntu based distro the output is always blank. I'm not sure if it has to do with the drivers, upstream bug in openCL that caused make LLAMA_CLBLAST=1 to fail or perhaps too small of a swap file (have plenty of memory to not have to use any swap, but could be a cause since swap memory seems to be generally handled awfully on linux). No errors, everything works fine, it just generates whitespace only.

Not related to streaming, since it's the same with or without. Is either related to how memory is dumped into swap on koboldcpp end (I have a micro-swap of 2gb, since following the normal formula of 1.5x would require an entire physical storage device for that in my case), upstream in one of the libs/dependencies or Nvidia drivers on linux I think. I know that unity has similar issues where shitty programming forces an entire memory dump into swap, causing it to crash if you have massive amounts of memory and very little swap. Maybe related.

@LostRuins might as well tag, not worth creating a new issue and probably related.

**Comment by LostRuins** [comment]
Is this still an issue? Is the output blank only in the terminal or also in the UI?

**Comment by AllesMeins** [comment]
Sorry, forgot to reply! My initial issue seems to be solved - thank you for the quick fix! i don't know about @bucketcat issue.
