### ISSUE TITLE
[Enhancement] Include version in the koboldcpp.exe filename when creating a release

### ISSUE THREAD

**Issue by TheTerrasque** [LostRuins/koboldcpp#134]
Right now each release have the same exe name - "koboldcpp.exe". It gets a bit confusing after a few downloaded releases which is which.

It would be nice to have the release version as part of the name, for example "koboldcpp.v1.17.exe"

**Comment by LostRuins** [comment]
That's actually for ease of use and compilation, mostly. The version number is displayed when opening the app, and also on the download page.

**Comment by VraethrDalkr** [comment]
I don't know if that's relevant for you, but I wrote a PowerShell script that checks what latest version is and it downloads the new .exe if a newer version is ready. Just make a text file with .ps1 extension and place it in the same folder than koboldcpp.exe. It also prompts the user to select between between all the models .bin files, but they have to be located in the same folder than koboldcpp.exe. Here's my script:

```
$uri = "https://api.github.com/repos/LostRuins/koboldcpp/releases/latest"
$version = (Invoke-WebRequest -Uri $uri -UseBasicParsing | ConvertFrom-Json).tag_name

if (Test-Path "version.txt") {
    $oldVersion = Get-Content "version.txt"
} else {
    $oldVersion = ""
}

if ($version -gt $oldVersion) {
    Start-BitsTransfer -Source "https://github.com/LostRuins/koboldcpp/releases/latest/download/koboldcpp.exe" -Destination "koboldcpp.exe" -DisplayName "Downloading koboldcpp.exe" -Priority High
    echo $version > version.txt
}

if ($version -eq $oldVersion) {
    Write-Host "`n$version is current`n" -ForegroundColor Yellow
} else {
    Write-Host "`nUpdated from $oldVersion to $version`n" -ForegroundColor Yellow
}

$binFiles = Get-ChildItem -Path $PSScriptRoot -Filter *.bin
$binFiles | ForEach-Object -Begin { 
    $i = 1 
} -Process { 
    Write-Host "$i. $($_.Name -replace '\.bin$')"
    $i++ 
} -End { 
    $choice = Read-Host "`nChoose a model"
    if ($choice -ge 1 -and $choice -le $binFiles.Count) { 
        & ".\koboldcpp.exe" --model $binFiles[$choice - 1].FullName --launch --psutil_set_threads --highpriority --smartcontext --useclblast 0 0 
    } else { 
        Write-Host "`nInvalid choice`n" 
    } 
}
```

**Comment by LostRuins** [comment]
That could be useful. I'd KIV it for now, but a non-intrusive cross platform way to get updates might be nice. I probably wouldn't go as far as to auto download it, instead directing them to the page so they can see the changelog before deciding.

**Comment by janvarev** [comment]
Hi!
Not sure about this change, because I have my custom BAT files for koboldcpp.exe. It's not good to change them every new version (or manually rename EXE file).

**Comment by LostRuins** [comment]
I actually agree with jan. The exe name should stay the same for ease of use. But you are free to rename your own exe files after downloading, they will still work.

**Comment by Zyril-8204** [comment]
@LostRuins - A dumb solution for everyone here. Can you possibly throw the release into a ziped file and have the folder zip be named KoboldCPP-(release number) with koboldcpp.exe inside it? Then those who want to differ between versioning for some reason have folders to do so automatically?

people like me and @VraethrDalkr would have to update some scripts to handle the zip file during a get latest relase, but it's not that difficult to do.

Personally I just move my current one to "old" folder and dowload/move in the latest to the root of my koboldcpp folder and have koboldcpp-old-stablemodel.bat and koboldcpp-model.bat. 

Only because I like to keep the latest + previous version incase something breaks between versions so I can verify it wasn't broken in previous version. However, having zip files with folder named with release number would probably make life a little easier for the "some" that don't use any automation.

**Comment by VraethrDalkr** [comment]
I made a very ugly command prompt single-line command that will show the latest version and then launch koboldcpp.exe. If someone have a use for it, here it is:

`curl -s https://api.github.com/repos/LostRuins/koboldcpp/releases/latest | findstr /c:"\"tag_name\":" | for /f "tokens=2 delims=:," %G in ('more') do @echo. & echo Latest version =%~G & echo. & koboldcpp.exe`
