### ISSUE TITLE
Win 7 exe: On launch, complains of missing dll(s)

### ISSUE THREAD

**Issue by cgessai** [LostRuins/koboldcpp#147]
**FWIW, I'm remoting into the Windows 7 machine using TightVNC but I've never had it cause issues with running program.**

When running the windows 7 exe on a windows 7 machine, nothing happens for about 15 seconds then a dialog window will appear with the title of "koboldcpp_win7.exe - System Error" and body of "The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer.  Try reinstalling the program to fix this problem." with an "OK" button.

However, in the CMD window which also appears is a different error:
D:\GPT>koboldcpp_win7.exe
Error loading Python DLL 'C:\Users\user\AppData\Local\Temp\_MEI41082\python39.dll'.
LoadLibrary: The specified module could not be found.

**Comment by LostRuins** [comment]
It seems like Windows 7 has other compatibility issues beyond koboldcpp - stuff like the pyinstaller python and other libraries are not working properly. I think supporting it will not be so easy.

**Comment by NBcobo** [comment]
Python 3.9 and above drops support for Windows 7. You may circumvent it by using the method by [nalexandru](https://github.com/nalexandru)
/
[api-ms-win-core-path-HACK](https://github.com/nalexandru/api-ms-win-core-path-HACK)
You can download the zip file api-ms-win-core-path-blender-0.3.1.zip from https://github.com/nalexandru/api-ms-win-core-path-HACK/releases/tag/0.3.1
Then "copy the **x86** dll into C:\Windows\SysWOW64 and the **x64** dll into C:\Windows\System32", which seems counter intuitive but works.
After this you may try the models provided by https://huggingface.co/Ejafa using oobagooba. That's all I can get so far. None of those ggml files work for me. Since the choice is so limited, I'll move to Windows 10 at last.

**Comment by LostRuins** [comment]
Yep I think suffice to say, it will be difficult to support windows 7 if even python has dropped support for it. I will leave the files I've already built up, but I don't think i'll be supporting windows 7 moving forward.
