### ISSUE TITLE
[Bug] Wrong parameters with RedPajama

### ISSUE THREAD

**Issue by paryska99** [LostRuins/koboldcpp#153]
Unless this is intended behaviour, kobold loads wrong parameters once it detects RedPajama based model.
Specifically the Blas setting was set to 512 batchsize but after detecting the model type it reloads the model in 256 batchsize.

**Comment by LostRuins** [comment]
This is intended, the blas batch sizes for non-llama models are capped at 256, because the estimation for memory per token is buggy, therefore extra memory has to be allocated. Currently, only LLAMA based models are able to utilizing batch sizes above 256 without issues or OOM. This should not really affect speed.

**Comment by paryska99** [comment]
Alright, thank you for the explanation
