### ISSUE TITLE
Chinese words process problem

### ISSUE THREAD

**Issue by xiaol** [LostRuins/koboldcpp#165]
I am not sure what happenning here, looks like tokenizer problem

as you can see https://github.com/saharNooby/rwkv.cpp/blob/1c363e6d5f4ec7817ceffeeb17bd972b1ce9d9d0/rwkv/chat_with_bot.py#LL169C18-L169C18

tokenizer is needed for process tokens, how do you bypass it?

i test koboldcpp on my phone with rwkv 7b model, but can't process words "你好” in chinese.

any advice would be very appreciate.

--------

i found this code 
https://github.com/LostRuins/koboldcpp/blob/c81dd58e763966a263fd8f13f5b2a99f7d8d201d/koboldcpp.py#L165

should use tokenizer instead?

**Comment by LostRuins** [comment]
I tried it, seems to be working for me. Depends on the model but the UTF-8 is encoding tokens and responding correctly.
![image](https://github.com/LostRuins/koboldcpp/assets/39025047/4819e959-0c5f-4522-9dc8-86cb08448ada)

**Comment by xiaol** [comment]
![Screenshot_2023-05-15-12-21-08-938_com.microsoft.emmx.jpg](https://github.com/LostRuins/koboldcpp/assets/1669515/20e4bae0-ac57-41a8-8c71-59cd45a44e68)

looks like this is Android version problem, did you test on ubuntu?

**Comment by xiaol** [comment]
there are few chinese models and amazing english models here ,https://huggingface.co/latestissue,
let me firgure out what happened here,

BTW what platform servering this model in the last screenshot?

**Comment by LostRuins** [comment]
it's just a normal chrome browser in mobile mode

**Comment by xiaol** [comment]
https://discord.gg/yxUX2RSQtE join us pls, rwkv cpp channel.

**Comment by simulanics** [comment]
---------------------------
KoboldCPP
---------------------------
Error:

File "socketserver.py", line 316, in _handle_request_noblock

  File "socketserver.py", line 347, in process_request

  File "socketserver.py", line 360, in finish_request

  File "koboldcpp.py", line 215, in __call__

  File "http\server.py", line 668, in __init__

  File "socketserver.py", line 747, in __init__

  File "http\server.py", line 433, in handle

  File "http\server.py", line 421, in handle_one_request

  File "koboldcpp.py", line 330, in do_POST

  File "encodings\cp1252.py", line 19, in encode

UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f31e' in position 10: character maps to <undefined>

----------------------------------------
---------------------------
OK   
---------------------------

I keep getting errors with the latest update for bad encodings. It prompts the error for unicode characters as well as chr(10) and chr(11). All data is in UTF-8 format, so all characters should be supported. It appears Koboldcpp is using Windows-1252 ANSII format (cp1252.py), causing the issue since the unicode characters don't exist in the character map? How do we fix this?

**Comment by LostRuins** [comment]
which model are you using? Sounds like it's a terminal limitation. I didn't change the way encoding is handled. You should be viewing it within the Lite UI to see UTF characters properly. I will add some extra checks before printing to console in the next version.

**Comment by LostRuins** [comment]
Closing this issue for now as resolved  in newest version. Please reopen if it's still a problem.

**Comment by xiaol** [comment]
![Screenshot_2023-06-07-21-06-31-991_com.microsoft.emmx.jpg](https://github.com/LostRuins/koboldcpp/assets/1669515/f5e7a4a8-1eb3-4735-a2bb-258551abdd52)

i have use newest version on my phone,still have this problem

![Screenshot_2023-06-07-21-09-42-026_com.termux.jpg](https://github.com/LostRuins/koboldcpp/assets/1669515/30cc830a-6f07-4e7c-bdc0-346ba5dc2476)

**Comment by LostRuins** [comment]
What version, and what model?

**Comment by xiaol** [comment]
![Screenshot_2023-06-08-22-49-07-969_com.microsoft.emmx.jpg](https://github.com/LostRuins/koboldcpp/assets/1669515/7f7b7ce1-349f-4bed-b9f1-7c8acf9c8b70)

![Screenshot_2023-06-08-22-53-34-070_com.microsoft.emmx.jpg](https://github.com/LostRuins/koboldcpp/assets/1669515/e25d3cbc-1344-40cb-aa33-9ebc0f1d83c0)

![Screenshot_2023-06-08-23-04-40-751_com.microsoft.emmx.jpg](https://github.com/LostRuins/koboldcpp/assets/1669515/4c2ad61c-6847-42c5-aa63-4f3f16a1d6c3)

![Screenshot_2023-06-08-23-05-00-677_com.microsoft.emmx.jpg](https://github.com/LostRuins/koboldcpp/assets/1669515/c7f13408-7625-48d0-9c38-3882c030f25a)

probably the sampler problem,in chatrwkv using this sampler with temp 1.2 topp 0.3，repeat penalty 0.4

**Comment by LostRuins** [comment]
Yes, try to use different sampler settings. The model and input are working - I see you can receive chinese text as a response. It's probably just configuration.

**Comment by xiaol** [comment]
thank you for your patiants,  
last post lost the url, https://github.com/BlinkDL/ChatRWKV/blob/e6b61645eca7be729684efc9d3cf9acdc77bb24a/rwkv_pip_package/src/rwkv/utils.py#L54

rwkv pip version have a specific sampler,how can it update to koboldcpp?

**Comment by LostRuins** [comment]
nucleus sampling is top-p
