### ISSUE TITLE
MPT Models Don't Work

### ISSUE THREAD

**Issue by NancyAurum** [LostRuins/koboldcpp#205]
It doesn't run the mpt-7b-instruct.ggmlv3.q8_0.bin from https://huggingface.co/TheBloke/MPT-7B-Instruct-GGML 

Command-line ggml, does run it, but a hassle to compile for Windows:
https://github.com/ggerganov/ggml/issues/211

**Comment by LostRuins** [comment]
Support for MPT models have not been added due to low demand and few available models

**Comment by NancyAurum** [comment]
> Support for MPT models have not been added due to low demand and few available models

MPT models have permissive license and are as good as Vicuna-7b.

**Comment by FNsi** [comment]
I found there's a wizard uncensored mpt story writer in hf [mpt-wizardlm-storywriter](https://huggingface.co/TehVenom/MPT-7b-WizardLM_Uncensored-Storywriter-Merge)

**Comment by NancyAurum** [comment]
> I found there's a wizard uncensored mpt story writer in hf [mpt-wizardlm-storywriter](https://huggingface.co/TehVenom/MPT-7b-WizardLM_Uncensored-Storywriter-Merge)

Does it really handle such large contexts? I.e. can you use it to summarize a book or extract a list of major characters with short descriptions?

**Comment by FNsi** [comment]
> > I found there's a wizard uncensored mpt story writer in hf [mpt-wizardlm-storywriter](https://huggingface.co/TehVenom/MPT-7b-WizardLM_Uncensored-Storywriter-Merge)
> 
> 
> 
> Does it really handle such large contexts? I.e. can you use it to summarize a book or extract a list of major characters with short descriptions?

I did try, and you should try it too. Tbh I think we should run it in interactive mode let it fully useful.

**Comment by FNsi** [comment]
> > > > I found there's a wizard uncensored mpt story writer in hf [mpt-wizardlm-storywriter](https://huggingface.co/TehVenom/MPT-7b-WizardLM_Uncensored-Storywriter-Merge)
> 
> > > 
> 
> > > 
> 
> > > Does it really handle such large contexts? I.e. can you use it to summarize a book or extract a list of major characters with short descriptions?
> 
> > 
> 
> > I did try, and you should try it too. Tbh I think we should run it in interactive mode let it fully useful.
> 
> 
> 
> I don't have a GPU to run pytorch.

And transformers support cpu mode, so

**Comment by LostRuins** [comment]
Hi, MPT model support has finally been added in the latest version. Do try it out.

**Comment by Yumpone** [comment]
I don't know if the gguf format is the problem but what ever MPT I run, I get an error. 
(
Welcome to KoboldCpp - Version 1.50
Setting process to Higher Priority - Use Caution
High Priority for Windows Set: Priority.NORMAL_PRIORITY_CLASS to Priority.HIGH_PRIORITY_CLASS
Attempting to use CLBlast library for faster prompt ingestion. A compatible clblast will be required.
Initializing dynamic library: koboldcpp_clblast.dll
==========
Namespace(bantokens=None, blasbatchsize=512, blasthreads=5, config=None, contextsize=8192, debugmode=0, forceversion=0, foreground=False, gpulayers=33, highpriority=True, hordeconfig=None, host='', launch=False, lora=None, model=None, model_param='C:\\KI\\LLM\\Models\\mosaicml-mpt-7b-8k-chat-Q6_K.gguf', multiuser=True, noavx2=False, noblas=False, nommap=False, noshift=False, onready='', port=5001, port_param=5001, preloadstory='', remotetunnel=False, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, tensor_split=None, threads=5, useclblast=[0, 0], usecublas=None, usemlock=False)
==========
Loading model: C:\KI\LLM\Models\mosaicml-mpt-7b-8k-chat-Q6_K.gguf
[Threads: 5, BlasThreads: 5, SmartContext: False, ContextShift: True]

ERROR: Detected unimplemented GGUF Arch: mpt
)

It does start but it runs weirdly. I am also wondering which Tokenizer to use since they are talking about using a tokenizer I never heard off. Might be a topic for a different threat tho.
