### ISSUE TITLE
Incorrect token benchmarks when generation is aborted

### ISSUE THREAD

**Issue by JHawkley** [LostRuins/koboldcpp#265]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Description of Issue

Using a LLaMa 65B model, I began generation with a 512 token limit and then aborted it after some amount of tokens had generated.  Observe the truncated log below:
```
Processing Prompt [BLAS] (1536 / 1536 tokens)
Generating (39 / 512 tokens)
Generation Aborted
Generating (513 / 512 tokens)
Time Taken - Processing:117.1s (76ms/T), Generation:55.8s (109ms/T), Total:172.9s (3.0T/s)
```

After the abort signal was sent at 39 tokens, it instantly jumped to 513 of 512 tokens being generated.  These not-actually-generated tokens are being included in the generation side of the benchmark, inappropriately reducing the average timing significantly.

The processing timing looks accurate, but the expected generation timing should be around 1430 ms/T, based on the 39 tokens actually generated and the 55.8 seconds that generation was timed at.

**Comment by gustrd** [comment]
I've observed that a similar issue arises when the <EOS> token is encountered. The current implementation computes the average tokens per second (T/s) as if all the requested tokens were generated. However, this doesn't accurately reflect the actual operation because the program stops generating further tokens once it hits the <EOS> token. Therefore, the computation should ideally consider only the tokens generated until the <EOS> token is reached for a more precise calculation of the average T/s.

**Comment by LostRuins** [comment]
Has been fixed some time back.
