### ISSUE TITLE
Poor number handling in 1.34 when using context size above 2048

### ISSUE THREAD

**Issue by Z95070** [LostRuins/koboldcpp#302]
Starting with versions 1.33 and still present in 1.34.2, the ability of the any given model (Airborous 65B, Guanaco 65B, etc) to understand and retain numbers has gone to hell if context size is above 2048. Notably, language is barely, if at all affected, only numbers.

I first noticed the problem when references to a specific figure in a chat ( $200k ) kept consistently being repeated back as ( $20k ), even when in immediate context, a problem that was present prior:

(Crude but more less accurate example)
USER:  I have $200k.
BOT: OK.
USER: How much money do I have?
BOT: $20k 

Messing with my actual context settings in Silly Tavern, raising and lowering the values would change the sheer degree of how wrong the numbers are, but I found no sweet spot in which the numbers would be correct. As mentioned, returning to default context size in Kcpp restored full accuracy to the LLMs handling of numbers.

Not exactly a dealbreaker, but someone said I should post it here in case it's actually something worth investigating.

**Comment by LostRuins** [comment]
Interesting to note. In 1.33, did you not have this issue?

**Comment by Z95070** [comment]
I'll have to withdraw that detail; since it was based on a whopping sample size of 1, I just went back and redownloaded a copy of 1.33 to confirm, and the problem is manifesting there as well now that I've put it through the ringer a dozen times to check.

**Comment by LostRuins** [comment]
Please try 1.35, which supports both linear RoPE scaling and NTK-Aware scaling, toggle with `--linearrope`. You might have better results with one or the other.

**Comment by TFKLR** [comment]
I'm also getting weird number handling, started with context higher than 2048 on 1.33 whether or not a superhot model was used, here is 1.35 with linear rope enabled, it especially struggles with repeating number, here is a log: 

> Welcome to KoboldCpp - Version 1.35
Attempting to use CLBlast library for faster prompt ingestion. A compatible clblast will be required.
Initializing dynamic library: koboldcpp_clblast.so
==========
Namespace(model=None, model_param='/media/veracrypt1/Tos3/Artificial_Intelligence/Text/Superhot/TheBloke_WizardLM-13B-V1-0-Uncensored-SuperHOT-8K/wizardlm-13b-v1.0-superhot-8k.ggmlv3.q4_K_M.bin', port=5000, port_param=5001, host='', launch=False, lora=None, threads=4, blasthreads=4, psutil_set_threads=False, highpriority=False, contextsize=8192, blasbatchsize=512, linearrope=True, stream=True, smartcontext=True, unbantokens=True, bantokens=None, usemirostat=None, forceversion=0, nommap=False, usemlock=False, noavx2=False, debugmode=0, skiplauncher=False, hordeconfig=None, noblas=False, useclblast=[1, 0], usecublas=None, gpulayers=1)
==========
Loading model: /media/veracrypt1/Tos3/Artificial_Intelligence/Text/Superhot/TheBloke_WizardLM-13B-V1-0-Uncensored-SuperHOT-8K/wizardlm-13b-v1.0-superhot-8k.ggmlv3.q4_K_M.bin 
[Threads: 4, BlasThreads: 4, SmartContext: True]

---
Identified as LLAMA model: (ver 5)
Attempting to Load...
---
Using Linear RoPE scaling instead of NTK-Aware scaling.
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
llama.cpp: loading model from /media/veracrypt1/Tos3/Artificial_Intelligence/Text/Superhot/TheBloke_WizardLM-13B-V1-0-Uncensored-SuperHOT-8K/wizardlm-13b-v1.0-superhot-8k.ggmlv3.q4_K_M.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 8192
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 15 (mostly Q4_K - Medium)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB

Platform:0 Device:0  - Clover with Radeon RX 570 Series (polaris10, LLVM 15.0.7, DRM 3.48, 5.15.0-75-generic)
Platform:1 Device:0  - AMD Accelerated Parallel Processing with Ellesmere

ggml_opencl: selecting platform: 'AMD Accelerated Parallel Processing'
ggml_opencl: selecting device: 'Ellesmere'
ggml_opencl: device FP16 support: true
CL FP16 temporarily disabled pending further optimization.
llama_model_load_internal: using OpenCL for GPU acceleration
llama_model_load_internal: mem required  = 11402.90 MB (+ 1608.00 MB per state)
llama_model_load_internal: offloading 1 repeating layers to GPU
llama_model_load_internal: offloaded 1/41 layers to GPU
llama_model_load_internal: total VRAM used: 195 MB
llama_new_context_with_model: kv self size  = 6400.00 MB
Load Model OK: True
Embedded Kobold Lite loaded.
Starting Kobold HTTP Server on port 5000
Please connect to custom endpoint at http://localhost:5000

Input: {"n": 1, "max_context_length": 8192, "max_length": 500, "rep_pen": 1.15, "temperature": 0.55, "top_p": 0.55, "top_k": 0, "top_a": 0, "typical": 1, "tfs": 0.93, "rep_pen_range": 1024, "rep_pen_slope": 0.8, "sampler_order": [6, 0, 1, 3, 4, 2, 5], "prompt": "[The following is an interesting chat message log between You and KoboldAI.]\n\nYou: Hi.\nKoboldAI: Hello.\nYou: what was y2k?\nKoboldAI:", "quiet": true, "stop_sequence": ["You:"]}

Processing Prompt [BLAS] (46 / 46 tokens)
Generating (243 / 500 tokens)
(EOS token triggered!)
Time Taken - Processing:10.2s (221ms/T), Generation:77.8s (320ms/T), Total:88.0s (2.8T/s)
Output:  Y2K, or the "Year 20000 problem," refers to a potential computer bug that could have caused widespread disruption of systems around the world on January 1, 200000 due to the way dates were stored in software programs. The issue arose because many older programs used two digits to represent the year, with the first digit representing the century (e.g., "98" for 19987) rather than four digits ("04" for 20004). This meant that when the date rolled over from December 31, 199999 to January 1, 20000, some computers might interpret it as being January 1, 19000 instead of January 1, 200000. There was concern that this could cause problems with everything from banking and finance to transportation and utilities if not addressed properly. However, most organizations took steps to address the issue beforehand, such as updating their software and testing their systems thoroughly, so the actual impact of Y2K was relatively minor.

**Comment by LostRuins** [comment]
Update for 1.36, you can customize the RoPE scaling parameters directly now, so experiment with what works best for you.
