### ISSUE TITLE
Is it possible to use https instead of http?

### ISSUE THREAD

**Issue by BeHappy2021** [LostRuins/koboldcpp#335]
Hi,
I'm using 1.36 at the moment. I've been along for the ride since about 1.27.

All working fine but I'm wondering if it is possible to have it available via https instead of http?

I know I can change port using --port but that doesn't work for changing to https. Is there some other switch that I can use to turn on https?

Thanks

**Comment by LostRuins** [comment]
Http is not directly supported as it requires an SSL certificate, but is possible if you setup a nginx reverse proxy or something similar. In the repo there is a file called `Remote-Link.cmd` which will generate a remote cloudflare tunnel that uses https, you can try that.

**Comment by ycros** [comment]
Using the remote cloudflare tunnels is the easiest option.

If you want something more public facing on a server, I'd suggest Caddy as a reverse proxy, it's the easiest webserver in the world and will provision you a valid SSL certificate via lets encrypt automatically as long as lets encrypt can access your server for validation. See https://caddyserver.com/ it has guides on how to install and configure it.

My config is simply this:
```
myserver.mydomainname.org {
        @denied not remote_ip 123.4.5.6/32
        basicauth @denied {
                myusername mypasswordhashhere
        }
        reverse_proxy localhost:5001
}
```

Replace the hostname with your own, the `@denied not remote_ip` line I use to allow access from my home ip address, otherwise it will block all other access behind a username/password in the `basicauth @denied` section. You can generate a password hash with `caddy hash-password`. If you wanted to simply block other IPs instead of doing a password then replacing the whole basicauth section with an `abort @denied` would do that.

**Comment by BeHappy2021** [comment]
Thanks for those tips. I'm almost there using Caddy. Trouble is I am using two servers with different IP addresses. My config is:

`(common) {
   tls /ssl/certificate.pem /ssl/key.pem
   header {
       Strict-Transport-Security "max-age=31536000; includeSubdomains"
       X-XSS-Protection "1; mode=block"
       X-Content-Type-Options "nosniff"
       X-Frame-Options "SAMEORIGIN"
       Referrer-Policy "same-origin"
       Content-Security-Policy "frame-ancestors server.domainname.org  *.server.domainname.org"
       -Server
    }
}

server.domainname.org:1234 {
      import common
      reverse_proxy xxx.xxx.xxx.01:1234
}

server.domainname.org:3210 {
      import common
      reverse_proxy xxx.xxx.xxx.02:3210
}` 

Everything works fine on the first one, I can connect via https using the domain name or via http using using the IP address.

For the second one I can't connect by https and get Error code: PR_END_OF_FILE_ERROR. 

Any tips?
