### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by ExeVirus** [LostRuins/koboldcpp#367]
# Pre-req:

Yes, I have read the readme.md and the license.txt file and have a decent understanding of the nuance of software licensing (Apache 2.0, LGPL, AGPL, etc.).

# Expected Behavior

Clear boundaries between what code is AGPL, and what is MIT.

# Current Behavior

Currently, these two are separated by this line:

```
Note that the above license applies ONLY to the GGML library and llama.cpp by ggerganov which are licensed under the MIT License
Kobold Lite by Concedo and the provided python ctypes bindings in koboldcpp.dll are licensed under the AGPL v3.0 License
```

# Actual Question(s):

### Can we have more clear boundaries as to what is determined to be committed under the AGPL license of Kobold?

Thanks in advance!

**Comment by LostRuins** [comment]
Sure. To clarify - **all** the contents of this repo are licensed under AGPL, that covers the embedded Kobold Lite UI, and the KoboldCpp source code submitted by myself and other contributors. This goes in line with other related Kobold projects such as KoboldAI United and AI Horde, which are similarly licensed, and ensures interoperability. 

However, the MIT license applies to code taken from "Upstream", that is ggerganov's repositories at https://github.com/ggerganov/llama.cpp and https://github.com/ggerganov/ggml , which are both licensed under MIT and irrevocably so. 

So unmodified common code from those repositories, such as the core GGML library itself, inference examples, and the CUDA kernels would be under MIT. Otherwise, you can treat all code that does not exist inside these upstream repos as under AGPL. 

Where I have contributed directly to upstream in specific pull requests (e.g. sending fixes for OpenCL to the llama.cpp repo), those modifications would be under MIT as well.
