### ISSUE TITLE
Streaming sometimes fails, even though generation succeeds.

### ISSUE THREAD

**Issue by mikehdt** [LostRuins/koboldcpp#394]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

KoboldCPP streams tokens.

# Current Behavior

Occasionally, usually after several generations and most commonly a few times after 'aborting' or stopping a generation, KoboldCPP will generate but not stream. Once it reaches its token limit, it will print the tokens it had generated. This means it's internally generating just fine, only that the streaming fails from time to time.

Once it has failed and fills out its context (printing the tokens it did generate to the terminal but not streaming them), then usually subsequent generations are fine to stream again until it does the same behaviour. This inconsistency does make it hard to pin down _why_ or _when_ it'll happen.

# Environment and Context

Using an RTX 4070 (12GB), 64GB system, Windows 11. Using KoboldCPP with SillyTavern, however it also happens from time to time with KoboldCPP's own internal web interface. This suggests to me that the problem is in initiating the streaming, or responding that it _is_ streaming.

The CLI params I'm using are `--stream --smartcontext --usecublas --gpulayers 40` (for a LLaMa 13B model)

# Steps to Reproduce

It's inconsistent, but not _rare_. I suspect it only happens after aborting generation a few times. It won't necessarily be the next generation after an abort. Let's say it's maybe 5% of the time?

It's been fairly consistently doing this for many versions now (at least since March?) so is likely something longer-term than eg. the CUDA build integration.

**Comment by LostRuins** [comment]
If it happens with Lite too, then it's not a problem with the streaming endpoint as Lite uses polled streaming instead, not SSE. 

What is likely happening is that the console (terminal) window is being paused, either because you click on it or something else is halting it's execution. 

Alternatively, the streaming might be delayed because the prompt is being processed. Check the console output to determine if it's halted, processing, or generating.

**Comment by mikehdt** [comment]
It may be both aspects, then?

I understand what you mean about watching the terminal; it's not that where you accidentally highlight some text or scroll up. The `Generating (x / y tokens)` does correctly update and progresses as expected, ticking upwards. It's more watching either Lite or Tavern just not stream any text from KoboldCPP to the UI - no tokens are sent during generation _sometimes_ (infrequently).

When it's done generating, the text is only in the terminal - as far as Lite or Tavern are concerned, no data has been received by them.

**Comment by LostRuins** [comment]
Okay then make sure Lite was launched with `--stream` (and refresh the browser window if it was already open!)

**Comment by mikehdt** [comment]
Yep, it is (as part of the CLI params in the report under `Environment and Context`).

The issue is that it streams correctly say ~98% of the time, but every once in a while it'll generate but _not_ stream. Then when it finishes generating, it puts its results into the terminal but _not_ send it to the UI.

I actually haven't used Lite in a little while so I'd need to double-check it occurs there - I have a memory of it doing that, but it most definitely occurs with Simple Proxy for Tavern / SillyTavern running with it.

**Comment by ThatDocBoi** [comment]
I also get it when I quickly abort and start again. Can there be a way to abort via console? Waiting for 2048 tokens at 0.7 T/s on my potato is a little rough not going to lie.

**Comment by Angela-BC** [comment]
A quick abort/retry when token generation is slow. Maybe when the abort/retry sequence is faster than the token generation speed?

**Comment by Ronny-apo** [comment]
I have mentioned the same in the last view days. Sometimes the streaming failed, even if the right endpoint was used. I have logged the error and in that case instead of sending the stream as data parts, the whole response is written. There is no data at all, just the regular response after processing/generating the tokens - like it was generated completely without any streaming. In most cases it is working fine.

**Comment by LostRuins** [comment]
Are you using multiuser mode? polled streaming is disabled when multiple requests are in the queue

**Comment by xXwatermelon** [comment]
This has been happening to me too. It happens a lot more consistently than others though.

When my cursor is not on the ST page, or tabbed into another window, it definitely will not stream, and only post it in the console, not ST. So it is generating, just not sending it. 

It happens almost 50% of the time, and I tried turning streaming off and that did not help whatsoever. 

It happens almost 90% of the time on swipes, not new replies.

**Comment by LostRuins** [comment]
That sounds like an issue with the ST client, not koboldcpp. If you turn streaming off, does it use the sync generate endpoint? Does it still have issues in that scenario?

By right, incoming server sent events that are not handled will get buffered, and will be received when the application returns back to the foreground. Try this simple example with koboldcpp:

`curl -XPOST http://127.0.0.1:5001/api/extra/generate/stream/ -N --http2 -H "Connection: keep-alive" -H "Content-Type: application/json" -H "Accept:text/event-stream" -d {\"n\":1,\"max_context_length\":2048,\"max_length\":50,\"rep_pen\":1.2,\"temperature\":0.7,\"top_p\":0.92,\"top_k\":0,\"top_a\":0,\"typical\":1,\"tfs\":1,\"rep_pen_range\":256,\"rep_pen_slope\":0.7,\"sampler_order\":[6,0,1,2,3,4,5],\"prompt\":\"hello\"}`

Tabbing back and forth, or pausing the terminal, will still result in all messages arriving at the end when focus returns.

Also pinging @Cohee1207 if they'd like to take a look.

**Comment by MoodCharge** [comment]
> A quick abort/retry when token generation is slow. Maybe when the abort/retry sequence is faster than the token generation speed?

yes, I tested that this problem happens more frequently when the generation speed is slower

**Comment by Ronny-apo** [comment]
> Are you using multiuser mode? polled streaming is disabled when multiple requests are in the queue

No, I don't use multiuser mode. I also don't use SillyTavern, but my own client. There are also no multiple connections. I checked this again yesterday, but it's definitely not the case. I have two problems. On the one hand, the streaming simply doesn't work at all from time to time and it outputs everything at once, but on the other hand (especially with 7B with full offload via GPU) it streams 30-40% and output then the rest on piece, as if he couldn't keep up. ​But problem two is more of a subtlety, with problem 1 it doesn't stream at all.

**Comment by LostRuins** [comment]
Can check if the latest version still has this issue? I have made some streaming api improvements.

**Comment by Ronny-apo** [comment]
It seems to have fixed my issue completely! Thank you for the fast fix, you're awesome!

**Comment by Ronny-apo** [comment]
Short update: Unfortunately I have noticed another issue now. While - in most cases - the streaming works fine, sometimes the model outputs the exact same message again in the next request (without doing any streaming), which is really weird. It does not happen all the time. After a re-generate, the text will be different, but without any streaming. When I then send another message, all is working fine again (including stream).

**Comment by LostRuins** [comment]
@Ronny-apo are you using Lite, ST or a different client? Do you get the exact same message as a full response, or just as a temporary "streaming" text?

**Comment by MoodCharge** [comment]
It pop out one token at first, then stopped streaming until it showed a chunk of tokens at the same time. Then it would get stuck and get this error in the console. (I get this error every time regardless of the streaming mode is turned on or off)
`Processing Prompt [BLAS] (67 / 67 tokens)
Generating (28 / 122 tokens)
(EOS token triggered!)
Time Taken - Processing:1.5s (22ms/T), Generation:6.8s (242ms/T), Total:8.3s (3.4T/s)
Output:  Sally would most likely be looking for the ball in the chest because that is where she last saw it before leaving the room.
Exception ignored in: <function Variable.__del__ at 0x000001E7288E24C0>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 363, in __del__
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001E7288E24C0>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 363, in __del__
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001E7288E24C0>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 363, in __del__
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001E7288E24C0>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 363, in __del__
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001E7288E24C0>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 363, in __del__
RuntimeError: main thread is not in main loop`

**Comment by LostRuins** [comment]
are you using sillytavern?

**Comment by MoodCharge** [comment]
> are you using sillytavern?

[koboldcpp.exe](https://github.com/LostRuins/koboldcpp/releases/download/v1.45.2/koboldcpp.exe)
yes, with his ST gui

**Comment by LostRuins** [comment]
I just tried with the latest sillytavern and koboldcpp, streaming is working perfectly. Make sure your nodejs and sillytavern is up to date.

**Comment by bubbabug** [comment]
> I just tried with the latest sillytavern and koboldcpp, streaming is working perfectly. Make sure your nodejs and sillytavern is up to date.

I am having the issue described in OP with latest exe version. Streaming is enabled in GUI and working on every other response in SillyTavern server. It only seems to happen every 7-10 responses, typically when prompt size increases. Error is as follows:

`Processing Prompt [BLAS] (880 / 880 tokens)
Generating (25 / 145 tokens)
(Stop sequence triggered: <
### Instruction:>)
Time Taken - Processing:19.5s (22ms/T), Generation:2.7s (107ms/T), Total:22.2s (1.1T/s)
Generation Aborted
Exception ignored in: <function Variable.__del__ at 0x0000021B86104790>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 363, in __del__
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000021B86104790>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 363, in __del__
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000021B86104790>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 363, in __del__
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000021B86104790>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 363, in __del__
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000021B86104790>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 363, in __del__
RuntimeError: main thread is not in main loop

Output: Alrighty, let's see how this goes. *starts typing slowly but surely*
### Instruction:
[WinError 10053] An established connection was aborted by the software in your host machine
Generate: The response could not be sent, maybe connection was terminated?
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 62749)
Traceback (most recent call last):
  File "socketserver.py", line 316, in _handle_request_noblock
  File "socketserver.py", line 347, in process_request
  File "socketserver.py", line 360, in finish_request
  File "koboldcpp.py", line 389, in __call__
  File "http\server.py", line 647, in __init__
  File "socketserver.py", line 747, in __init__
  File "http\server.py", line 429, in handle
  File "http\server.py", line 395, in handle_one_request
  File "socket.py", line 669, in readinto
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
----------------------------------------`

It appears to be a consistent issue on my setup, and while not causing crashes or otherwise impacting usage except for random wait times, it is quite annoying. I had the idea that this may be browser related, but I am unable to change browsers as I would lose my TTS and STT functionality.

**Comment by MoodCharge** [comment]
> I just tried with the latest sillytavern and koboldcpp, streaming is working perfectly. Make sure your nodejs and sillytavern is up to date.

Thanks

**Comment by mikehdt** [comment]
I've also noticed that this seems to be resolved since at least a version or two. I haven't noticed it misbehave for a while. I'll close out this comment, but please reopen if something new comes to light.
