### ISSUE TITLE
Koboldcpp.exe has more functionality then webUI, but I'm using MacOS

### ISSUE THREAD

**Issue by yukiarimo** [LostRuins/koboldcpp#468]

**Comment by neph1** [comment]
Use python? Check the "OSX and Linux" section in the readme.

**Comment by beebopkim** [comment]
You need to make a *Python Virtual Environment* for your koboldcpp. It is usually done by typing 'python3 -m venv pyenv' in shell prompt in Terminal. I recommend to install python separately rather than using python included in macOS in koboldcpp directory. After doing this, you can activate your virtual environmet by typing 'source pyenv/bin/activate'. Then, 'pip install -r requirements.txt' must be followed up. After doing this, you can run 'python koboldcpp.py'.

**Comment by yukiarimo** [comment]
Yeah I know. I was talking about different problem. Look at my Reddit post: https://reddit.com/r/LocalLLaMA/s/MZMHrCtv10

I noticed that BLAS processing is slow for me, and I can’t change it in the WebUI, but Windows user who are using .exe can do this in the different UI started by this CUDA.exe file in releases. Is there any way to make BLAS faster, like how to get those functions and configuration options, which are not available in the WebUI?

**Comment by LostRuins** [comment]
BLAS should be relatively fast on macOS with accelerate already. If you want you can try Metal which will be even faster, just `make LLAMA_METAL=1`

**Comment by yukiarimo** [comment]
It fast enough, but why it is working like for example:

[BLAS]: 512 / 1024
[BLAS]: 1024 / 1024

is it possible to process with 1024 chunks?

**Comment by LostRuins** [comment]
Yes you can set your BLAS batch size

**Comment by yukiarimo** [comment]
Where?

**Comment by LostRuins** [comment]
https://github.com/LostRuins/koboldcpp/wiki#what-is-blas-what-is-blasbatchsize-how-does-it-affect-me

**Comment by yukiarimo** [comment]
Thanks it helps
