### ISSUE TITLE
UI thinks the backend is idle when it's busy

### ISSUE THREAD

**Issue by actually-a-cat** [LostRuins/koboldcpp#478]
It's possible to end up in a state where the Lite frontend thinks the backend is idle and ready, while it's actually running a generation that is going nowhere. The most reliable way is to (accidentally) close the browser tab while a generation is running then reopen it, but it's also happened to me with some combination of Back, Retry and Abort buttons (I can't reproduce it, but I've seen it multiple times).

This locks up the application: new requests will fail, the Abort button isn't present, and the only options are to wait until generation ends (which can be a very long time with a slow model) or restart the backend. The latter can be annoying if the backend is running on another computer, I have to keep an SSH session open for that purpose while using Kobold.

Ideally this would not happen at all, but I'd be happy with just an addition of a quick way to resolve it without restarting the whole thing, maybe an always-available abort button, or one on the "Error, server is busy" popup.

**Comment by LostRuins** [comment]
will be fixed in next version, i will add an option to abort on busy popup

**Comment by LostRuins** [comment]
It should be fixed now.

**Comment by aleksusklim** [comment]
For me this happens each time a have a long prompt for BLAS to digest. I suspect that something is stuck in "blas batch" even after the server prints "Generation Aborted".

Now it is clear that even if the user forcefully aborts the pending request twice, it is still won't pop from internal BLAS processing, and has to leave it naturally.

It take roughly the same amount of time from the initialed abort to (1) have the server functional again, and (2) for yellow text starting to appear if we don't abort. (I mean, it looks like it could be aborted only when generating, not digesting).

This won't happen after pure "Retry", because the prompt is already processed. But each time I submit a new line, or making changes in history – it becomes impossible to abort that! It would take the same amount of time as if I'll wait for yellow text to appear – to abort after that.

I think, the larger the BLAS batch size, the longer it would hang after processing and aborting, because it could abort itself only between batches. Right?

Still present in 1.47.2

**Comment by LostRuins** [comment]
Yes, you cannot abort a batch that is currently processing. What you can do is set your blasbatchsize to a smaller value, then if it was processing 128/2000 and you abort, it will stop when reaching 256/2000. Once a batch has started calculating it cannot be stopped.

**Comment by aleksusklim** [comment]
Okay, that explains!

I see the minimal batch size is 32. I'll check, how much of slowdown it gives when used instead of default value. Maybe it would be acceptable to keep it low.
