### ISSUE TITLE
kobold deleted itself?

### ISSUE THREAD

**Issue by oobedootoot** [LostRuins/koboldcpp#534]
i tried to load it twice, might have mistyped something i dont remember, but it didnt work. i tried a third time it kept saying access denied. i go to look at the file and the koboldcpp file has 0 bytes. like it deleted itself but left the file? this has never happened with other version of koboldcpp

**Comment by LostRuins** [comment]
KoboldCpp will never delete itself. Do you have some sort of antivirus that's flagging it as a false positive? Otherwise, the download may have issues. 

Make sure you only obtain KoboldCpp from official sources (e.g. this github)

**Comment by aleksusklim** [comment]
I saw viruses that infect executables (as .EXEs are discovered) and inject their virus code there.
Then an antivirus might see it and delete the file, but fail to disarm the active copy of the virus in the system!

Other symptoms of such a virus are:
- You run a program and it works; you run it again and see a fatal error, which is fixed by redownloading/reinstalling.
- The file size of extracted EXE is not equal to its file size in distribution.
- Files disappearing in front of your eyes after any interaction with them, when antivirus sees that kind of infection.

**Comment by LostRuins** [comment]
You should compare the exe file you have with the official downloads available on Github. Alternatively, you can download the source code and compile it yourself.
