### ISSUE TITLE
See the used seed number after generation.

### ISSUE THREAD

**Issue by wlad-pescenko** [LostRuins/koboldcpp#590]
Hello,
Could it be possible to add the seed used when the output is written on the terminal?
I sometimes like the output provided but I am unable to repeat it. The idea would be to "fine-tune" the output.

**Comment by LostRuins** [comment]
If the seed is not provided, the current system time is used as the seed, which is not currently stored after initializing. It could potentially be added in future.

For now, you could consider setting the `sampler_seed` which allows you to use any seed you want. 

Storing the seed isn't the best solution though, because there's no relevance between the seed used and the quality of the output. Rather, you should save the generations that you like to file so you can reload them again later - quick save slots may be useful for that purpose.

**Comment by VL4DST3R** [comment]
Storing generation info is something I would also like to have, especially knowing what models were used.

It would have come in very useful a number of times now, especially with older exported texts as it can be a bit disappointing when you forget what you used back then and try to continue from where you left off only to see it be in a different style.

I know you can realistically change the model mid-text or manually edit it to more or less invalidate any metadata stored, but it would be nice regardless, at least as a general guideline if one tries to continue or reproduce the original results.

Maybe take the model info similar to how it is provided to the UI in the `last request served by X using koboldcpp/dolphin-2.6-mixtral-8x7b.Q5_K_M in 26.5 seconds.` so we have the last used model to generate an output?

**Comment by LostRuins** [comment]
fair enough. I will add the last used seed to the perf endpoint

**Comment by LostRuins** [comment]
Already fixed
