### ISSUE TITLE
Load custom background image from command line

### ISSUE THREAD

**Issue by CorentinWicht** [LostRuins/koboldcpp#597]
Dear Developpers, 

I have just seen that as of [version 1.54](https://github.com/LostRuins/koboldcpp/releases/tag/v1.54) you "_added support for custom background images_" which is a very good idea to personalize the interface.

Nevertheless, would it be possible to add the background image (e.g., URL) as a parameter of the .json file provided to the `--preloadstory` argument? Currently, the only option I see is to manually load an image in the GUI, but since we are making koboldcpp GUI accessible to our University Community on a web server, we cannot "force" the same background image to all our users (it would only apply locally).

Many thanks,

C.

**Comment by LostRuins** [comment]
At the moment this isn't possible, since the image is not part of the saved json file but rather something else stored locally. It can be considered in future, but I do want to avoid bloating the save file, since most backgrounds will end up being a few MB in size which would make the file very large and saving would become very slow.
