### ISSUE TITLE
[OVERSIGHT] Dynatemp range capped at 2.

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#607]
As I understand it, Kalomaze's Dynatemp is being added into mainline KoboldCPP.  However, the latest implementation of his prototype KoboldCPP build only allows for a range of 2.   The Yix-Tral 2x30b model works better with a temperature of 4, having more creativity and fewer repetition traps.   The official implementation should allow the maximum range (5), to ensure the best model output.

**Comment by LostRuins** [comment]
Good point! Will change it to 5.

**Comment by LostRuins** [comment]
Should be fixed in the latest release

**Comment by SabinStargem** [comment]
There is an oddity, maybe two.

1:  If you click the 'help' button below Dynatemp, the range is altered.  It looks to be random, I got a 7.77ish range, and a 5.2.

2:  I can't tell whether DynaTemp is being used.  For Kalomaze's older builds, they generated a report about token probabilities.   Their latest build and v1.55 don't report.  A prior build of Dynatemp UI had a checkbox for enabling and disabling Dynatemp.  I am thinking that there is a possibility that UI element wasn't incorporated with the latest UI iteration, and DynaTemp might be disabled because of it.

**Comment by LostRuins** [comment]
Dynatemp is being used as long as dynatemp range > 0 - to confirm, you can run it with a fixed seed and then adjust the dynatemp range and see if the output changes - or run in debug mode and observe the token probabilities as you change dynatemp. 

There's no checkbox for disabling it, it's disabled if set to 0 or below.

Clicking the "Help" button shows a min and max dynamic temp instead of the range, but both values can be converted.

**Comment by Azirine** [comment]
What exponent value is used in this implementation? Can it be changed? As I understand different exponent values affect results dramatically.
https://rentry.org/dynamic_temperature
