### ISSUE TITLE
CLblast argument does not use GPU

### ISSUE THREAD

**Issue by ponyguru** [LostRuins/koboldcpp#84]
When launching with arguments --useclblast 0 0 to 8 8 and --smartcontext, only the cpu is used. The application does not crash like is suggested by other users. It successfully initializes the clblast.dll, but regardless of arguments used in --useclblast, it only ever uses the cpu. In addition, regardless of which model I use I receive this error: https://imgur.com/a/h54ybwB. However, this error does not crash the program, I can still generate - just only with my cpu.

Windows 10
AMD 6700XT
Ryzen 3600

**Comment by LostRuins** [comment]
That error you see if because it is loading your model in a compatibility mode - your model file is outdated (made for earlier ggml format). 

Also currently `--useclblast` is only tested and supported for LLAMA models. 
However, the new format of GPT-J supports using OpenBLAS.

To obtain the latest ggml pygmalion which is faster and supports OpenBLAS, try this link: https://huggingface.co/concedo/pygmalion-6bv3-ggml-ggjt/tree/main 

and download the q4_0 version

**Comment by LostRuins** [comment]
Closing this issue as it seems to have been resolved, do open it if there are further problems.
