### ISSUE TITLE
Cannot initialize microphone (non-localhost URL)

### ISSUE THREAD

**Issue by CorentinWicht** [LostRuins/koboldcpp#920]
Dear @LostRuins,

I am trying to link my koboldcpp server running on port 8008 with the Alltalk server running on 7851 (default), on the same virtual machine.

I have opened the corresponding firewall ports and can reach each service individually via the public ip address/alias:
![image](https://github.com/LostRuins/koboldcpp/assets/52161904/9865560c-5257-425f-b8e3-a8a764020d48)
![image](https://github.com/LostRuins/koboldcpp/assets/52161904/5dcc6d4b-9f8a-49f1-a2e0-72a2a2a3b050)

I can successfully link them both in koboldcpp settings:
![image](https://github.com/LostRuins/koboldcpp/assets/52161904/b2ec18ae-bc24-4a7c-a5c6-b50022be0ffc)
![image](https://github.com/LostRuins/koboldcpp/assets/52161904/feb6c1ec-dba4-421a-9e0a-39780efeddc9)

I have two issues here:

1. Though I do not get an error, there is not sound coming out when I run the ![image](https://github.com/LostRuins/koboldcpp/assets/52161904/fb682d0a-091f-4261-b84d-185b266ede9c) or when the AI responses to a query.
2. When I set ![image](https://github.com/LostRuins/koboldcpp/assets/52161904/b0f4a890-fc29-4724-8e0c-c805c4565dc4), I get the following error:
![image](https://github.com/LostRuins/koboldcpp/assets/52161904/c73a4adb-fdfc-4442-96a7-86bd3c975519)

For context, we are running an instance of koboldcpp on a linux RHEL9 virtual machine whose accessible to our University community inside our network only.

Best,

C.

**Comment by LostRuins** [comment]
1. For the first item, can you check if there's audio being output if TTS is set to the browser built-in TTS instead? I'm not sure about AllTalk, but XTTS api server had a streaming mode based on launch flags, where the audio is output from the server side when streamed instead, so if that exists it should be turned off. You can take a look at the browser network tab to see if the audio is actually generated and received correctly. Perhaps @erew123 can take a look too.

2. For Whisper speech control - This is a common issue but it has nothing to do with Koboldcpp, but rather, this is a modern browser security setting that prevents the use of microphone for any webpage content not served over https. Koboldcpp does allow custom or self-signed SSL certs which should solve this issue - alternatively you can use a service like Cloudflare to perform SSL offloading via a proxy. If you *can only* use http, then the browser itself needs to have a flag to allow it: See https://stackoverflow.com/questions/52759992/how-to-access-camera-and-microphone-in-chrome-without-https in order for a microphone to work.

The browser security restriction does not affect localhost which is why it works there even with http.

**Comment by CorentinWicht** [comment]
> 1. For the first item, can you check if there's audio being output if TTS is set to the browser built-in TTS instead? I'm not sure about AllTalk, but XTTS api server had a streaming mode based on launch flags, where the audio is output from the server side when streamed instead, so if that exists it should be turned off. You can take a look at the browser network tab to see if the audio is actually generated and received correctly. Perhaps @erew123 can take a look too.
> 
> The browser security restriction does not affect localhost which is why it works there even with http.

Thanks for your support!

I confirm that if I set TTS to my browser built-in TTS system (Brave Browser), sound comes out properly:
![image](https://github.com/LostRuins/koboldcpp/assets/52161904/08d4f5d8-78eb-40e1-8c99-de7136caae3b)

I unfortunately don't see a setting in Alltalk where I could de-/activate the streaming mode:
![image](https://github.com/LostRuins/koboldcpp/assets/52161904/6ec40040-50cd-4176-898d-0558e8dec57f)

Overall, Is there a wiki somewhere which guides user into connecting koboldcpp and alltalk? 
In fact, now I am not even able to link them both...
![image](https://github.com/LostRuins/koboldcpp/assets/52161904/3c7e07b1-e2c5-494f-b9bf-7a31b5e3be86)

Even though the URL is correct and the API is ready to accept requests:
![image](https://github.com/LostRuins/koboldcpp/assets/52161904/e3810416-29ca-4b3e-8c14-0fee7461fc0f)

> 2. For Whisper speech control - This is a common issue but it has nothing to do with Koboldcpp, but rather, this is a modern browser security setting that prevents the use of microphone for any webpage content not served over https. Koboldcpp does allow custom or self-signed SSL certs which should solve this issue - alternatively you can use a service like Cloudflare to perform SSL offloading via a proxy. If you _can only_ use http, then the browser itself needs to have a flag to allow it: See https://stackoverflow.com/questions/52759992/how-to-access-camera-and-microphone-in-chrome-without-https in order for a microphone to work.

Regarding Whisper, I will investigate it further but we are in fact serving our webpage content over https using a load-balancer (Kemp).

**Comment by LostRuins** [comment]
It will probably be super slow, but you can try the colab launch script for alltalk which did work for me previously, see https://github.com/erew123/alltalk_tts/issues/235

Try the colab setup and copy the cloudflare tunnel URL as the alltalk endpoint - see if that works when you generate a short test voice. Unfortunately, I don't have any further documentation that can help, you'd have to check with @erew123 regarding alltalk.

**Comment by erew123** [comment]
Hi @CorentinWicht & @LostRuins 

I can confirm there is a complication on AllTalk v1 with getting the API to work over tunnelling. Which is why I'm on with V2, which resolves this issue (or should do). [beta](https://github.com/erew123/alltalk_tts/tree/alltalkbeta)

I have been working on getting Google Colab working, which is 90% working now with one or two caveats e.g. RVC voices don't work yet on Colab. Colab was my first push before working on Docker or other systems as I knew it would be the hardest of the technical challenges, meaning, if I can get it working there, it should work on any other systems.

Saying all that though, there are some required changes needed to make the BETA work with Kobold as there are some changes to the API response [detailed here](https://github.com/erew123/alltalk_tts/issues/166) and generally speaking the API suite has been expanded. I was hoping to have colab ready by now, but, there have also been a few fires to put on with the beta so, that's dug into my time.

Ill reply to you @LostRuins on the other ticket, as it would be handy for us to keep things in one place I can track.

Thanks

**Comment by erew123** [comment]
Oh, and the Streaming endpoint and Standard generation endpoints are 2x different endpoints. So its not something you set within AllTalk, but you have to make a call to a different endpoint. And of course, because on AllTalk v2, some of the TTS engines will not support streaming, streaming may or may not be available, depending on the TTS engine you load in. (this information is reported back to the client system via the "currentsettings" api/endpoint on V2)

**Comment by LostRuins** [comment]
Did you manage to get this sorted?

**Comment by CorentinWicht** [comment]
> Did you manage to get this sorted?

Thanks for your support @LostRuins and @erew123.

I have uninstalled Alltalk V1 and moved to the [V2 beta version](https://github.com/erew123/alltalk_tts/tree/alltalkbeta) which works nicely and can be accessed through http (but not https).
I can also link both koboldcpp and alltalk v2 without errors but no sound is coming out (while it works if I use my browser TTS).

I will investigate further and keep you updated.

**Comment by CorentinWicht** [comment]
> > Did you manage to get this sorted?
> 
> Thanks for your support @LostRuins and @erew123.
> 
> I have uninstalled Alltalk V1 and moved to the [V2 beta version](https://github.com/erew123/alltalk_tts/tree/alltalkbeta) which works nicely and can be accessed through http (but not https). I can also link both koboldcpp and alltalk v2 without errors but no sound is coming out (while it works if I use my browser TTS).
> 
> I will investigate further and keep you updated.

Just a tiny improvement: sound comes out now properly (only in http though).
My mistake was, when I installed the Alltalk V2 beta version, I downloaded the "Piper" model and it seems that koboldcpp instead requires the [XTTS V2 model](https://huggingface.co/coqui/XTTS-v2).

**Comment by CorentinWicht** [comment]
For your information, we managed to serve the Alltalk service over https (by opening port 8443) through our Load Balancer (Kemp) and both TTS and Whisper speech control works perfectly, thanks for the support !

**Comment by CorentinWicht** [comment]
By the way, I did not find a parameter corresponding to "Speech Control" (
![image](https://github.com/LostRuins/koboldcpp/assets/52161904/de917cf7-5c2b-459d-a445-4c15c59e76dd)
) in the .json file that can be provided with command-line argument `--preloadstory`.

Is it intentional not to include this default parameter ?
It would be quite useful to be able to provide it to all our users.

Best,

C.

**Comment by LostRuins** [comment]
Ah, this parameter cannot be set from the json file as modern browsers require a page interaction followed by a popup prompt asking microphone permission before it is granted. 

So a brand newly opened instance cannot immediately self-enable the microphone, thus I did not preserve that setting in the save file. I could make it auto prompt for mic access when you start interacting with the page, but that seems kind of intrusive since many spammy websites do that.

**Comment by CorentinWicht** [comment]
> Ah, this parameter cannot be set from the json file as modern browsers require a page interaction followed by a popup prompt asking microphone permission before it is granted.
> 
> So a brand newly opened instance cannot immediately self-enable the microphone, thus I did not preserve that setting in the save file. I could make it auto prompt for mic access when you start interacting with the page, but that seems kind of intrusive since many spammy websites do that.

Yes you are right, I did not foresee how intrusive this would be.. Better leave it off then and letting each one the choice to activate the functionality at some point.

Thanks for support and best wishes,

C.
